### Importing Libraries

In [7]:
import numpy as np


### Create a NumPy array of random numbers


arr = np.random.rand(3, 4)
print("Original Array:")
print(arr)


### Calculate the mean, median, and standard deviation

In [8]:

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 0.5124596745840347
Median: 0.5199849951647827
Standard Deviation: 0.2507898427275767


### Perform element-wise operations

In [9]:

arr_add = arr + 2  # addition
arr_mul = arr * 2  # multiplication
print("\nElement-wise Addition:")
print(arr_add)
print("\nElement-wise Multiplication:")
print(arr_mul)


Element-wise Addition:
[[2.0198952  2.44800551 2.49542107 2.14860708]
 [2.54454892 2.54979307 2.93479551 2.72937976]
 [2.86788087 2.43229826 2.40686622 2.57202462]]

Element-wise Multiplication:
[[0.03979041 0.89601102 0.99084214 0.29721416]
 [1.08909784 1.09958614 1.86959102 1.45875951]
 [1.73576174 0.86459653 0.81373243 1.14404925]]


### Reshape the array

In [10]:

arr_reshaped = arr.reshape(4, 3)
print("\nReshaped Array:")
print(arr_reshaped)



Reshaped Array:
[[0.0198952  0.44800551 0.49542107]
 [0.14860708 0.54454892 0.54979307]
 [0.93479551 0.72937976 0.86788087]
 [0.43229826 0.40686622 0.57202462]]


### Perform matrix multiplication

In [11]:

mat_mul = np.dot(arr, arr_reshaped)
print("\nMatrix Multiplication:")
print(mat_mul)


Matrix Multiplication:
[[0.59433258 0.67468738 0.77114021]
 [1.2816893  1.52193104 1.80056775]
 [0.70913121 1.15372044 1.34796463]]
